<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarTypeAccessoire', 'doctrine');

/**
 * BaseCarTypeAccessoire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtypeacc
 * @property string $title
 * @property string $description
 * @property integer $active
 * @property Doctrine_Collection $CarAccessoire
 * 
 * @method integer             getIdtypeacc()     Returns the current record's "idtypeacc" value
 * @method string              getTitle()         Returns the current record's "title" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method integer             getActive()        Returns the current record's "active" value
 * @method Doctrine_Collection getCarAccessoire() Returns the current record's "CarAccessoire" collection
 * @method CarTypeAccessoire   setIdtypeacc()     Sets the current record's "idtypeacc" value
 * @method CarTypeAccessoire   setTitle()         Sets the current record's "title" value
 * @method CarTypeAccessoire   setDescription()   Sets the current record's "description" value
 * @method CarTypeAccessoire   setActive()        Sets the current record's "active" value
 * @method CarTypeAccessoire   setCarAccessoire() Sets the current record's "CarAccessoire" collection
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarTypeAccessoire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_type_accessoire');
        $this->hasColumn('idtypeacc', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CarAccessoire', array(
             'local' => 'idtypeacc',
             'foreign' => 'idtypeacc'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}