<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarBoite', 'doctrine');

/**
 * BaseCarBoite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idboite
 * @property string $title
 * @property string $description
 * @property integer $active
 * @property CarAuto $CarAuto
 * 
 * @method integer  getIdboite()     Returns the current record's "idboite" value
 * @method string   getTitle()       Returns the current record's "title" value
 * @method string   getDescription() Returns the current record's "description" value
 * @method integer  getActive()      Returns the current record's "active" value
 * @method CarAuto  getCarAuto()     Returns the current record's "CarAuto" value
 * @method CarBoite setIdboite()     Sets the current record's "idboite" value
 * @method CarBoite setTitle()       Sets the current record's "title" value
 * @method CarBoite setDescription() Sets the current record's "description" value
 * @method CarBoite setActive()      Sets the current record's "active" value
 * @method CarBoite setCarAuto()     Sets the current record's "CarAuto" value
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarBoite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_boite');
        $this->hasColumn('idboite', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CarAuto', array(
             'local' => 'idboite',
             'foreign' => 'idboite'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}