<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarPromotion', 'doctrine');

/**
 * BaseCarPromotion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idpromotion
 * @property integer $idcon
 * @property integer $idauto
 * @property integer $prix
 * @property timestamp $datedebut
 * @property timestamp $datefin
 * @property integer $active
 * @property CarAuto $CarAuto
 * @property CarCon $CarCon
 * 
 * @method integer      getIdpromotion() Returns the current record's "idpromotion" value
 * @method integer      getIdcon()       Returns the current record's "idcon" value
 * @method integer      getIdauto()      Returns the current record's "idauto" value
 * @method integer      getPrix()        Returns the current record's "prix" value
 * @method timestamp    getDatedebut()   Returns the current record's "datedebut" value
 * @method timestamp    getDatefin()     Returns the current record's "datefin" value
 * @method integer      getActive()      Returns the current record's "active" value
 * @method CarAuto      getCarAuto()     Returns the current record's "CarAuto" value
 * @method CarCon       getCarCon()      Returns the current record's "CarCon" value
 * @method CarPromotion setIdpromotion() Sets the current record's "idpromotion" value
 * @method CarPromotion setIdcon()       Sets the current record's "idcon" value
 * @method CarPromotion setIdauto()      Sets the current record's "idauto" value
 * @method CarPromotion setPrix()        Sets the current record's "prix" value
 * @method CarPromotion setDatedebut()   Sets the current record's "datedebut" value
 * @method CarPromotion setDatefin()     Sets the current record's "datefin" value
 * @method CarPromotion setActive()      Sets the current record's "active" value
 * @method CarPromotion setCarAuto()     Sets the current record's "CarAuto" value
 * @method CarPromotion setCarCon()      Sets the current record's "CarCon" value
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarPromotion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_promotion');
        $this->hasColumn('idpromotion', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('idcon', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('idauto', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('prix', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('datedebut', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('datefin', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CarAuto', array(
             'local' => 'idauto',
             'foreign' => 'idauto',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CarCon', array(
             'local' => 'idcon',
             'foreign' => 'idcon',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}