<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarImage', 'doctrine');

/**
 * BaseCarImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idimage
 * @property string $image
 * @property Doctrine_Collection $CarImages
 * 
 * @method integer             getIdimage()   Returns the current record's "idimage" value
 * @method string              getImage()     Returns the current record's "image" value
 * @method Doctrine_Collection getCarImages() Returns the current record's "CarImages" collection
 * @method CarImage            setIdimage()   Sets the current record's "idimage" value
 * @method CarImage            setImage()     Sets the current record's "image" value
 * @method CarImage            setCarImages() Sets the current record's "CarImages" collection
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_image');
        $this->hasColumn('idimage', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('image', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '200',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CarImages', array(
             'local' => 'idimage',
             'foreign' => 'idimage'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}