<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ip2country', 'doctrine');

/**
 * BaseIp2country
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ip_from
 * @property integer $ip_to
 * @property string $country_code2
 * @property string $country_code3
 * @property string $country_name
 * 
 * @method integer    getIpFrom()        Returns the current record's "ip_from" value
 * @method integer    getIpTo()          Returns the current record's "ip_to" value
 * @method string     getCountryCode2()  Returns the current record's "country_code2" value
 * @method string     getCountryCode3()  Returns the current record's "country_code3" value
 * @method string     getCountryName()   Returns the current record's "country_name" value
 * @method Ip2country setIpFrom()        Sets the current record's "ip_from" value
 * @method Ip2country setIpTo()          Sets the current record's "ip_to" value
 * @method Ip2country setCountryCode2()  Sets the current record's "country_code2" value
 * @method Ip2country setCountryCode3()  Sets the current record's "country_code3" value
 * @method Ip2country setCountryName()   Sets the current record's "country_name" value
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseIp2country extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_ipcountry');
        $this->hasColumn('ip_from', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ip_to', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('country_code2', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('country_code3', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('country_name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}