<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarPrestation', 'doctrine');

/**
 * BaseCarPrestation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idprestation
 * @property string $type
 * @property integer $prix
 * @property integer $active
 * @property Doctrine_Collection $CarPrestations
 * @property Doctrine_Collection $CarAutoPrestations
 * 
 * @method integer             getIdprestation()       Returns the current record's "idprestation" value
 * @method string              getType()               Returns the current record's "type" value
 * @method integer             getPrix()               Returns the current record's "prix" value
 * @method integer             getActive()             Returns the current record's "active" value
 * @method Doctrine_Collection getCarPrestations()     Returns the current record's "CarPrestations" collection
 * @method Doctrine_Collection getCarAutoPrestations() Returns the current record's "CarAutoPrestations" collection
 * @method CarPrestation       setIdprestation()       Sets the current record's "idprestation" value
 * @method CarPrestation       setType()               Sets the current record's "type" value
 * @method CarPrestation       setPrix()               Sets the current record's "prix" value
 * @method CarPrestation       setActive()             Sets the current record's "active" value
 * @method CarPrestation       setCarPrestations()     Sets the current record's "CarPrestations" collection
 * @method CarPrestation       setCarAutoPrestations() Sets the current record's "CarAutoPrestations" collection
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarPrestation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_prestation');
        $this->hasColumn('idprestation', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('type', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('prix', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CarPrestations', array(
             'local' => 'idprestation',
             'foreign' => 'idprestation'));

        $this->hasMany('CarAutoPrestations', array(
             'local' => 'idprestation',
             'foreign' => 'idprestation'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}