<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarAdresseGar', 'doctrine');

/**
 * BaseCarAdresseGar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idadressegar
 * @property integer $idgar
 * @property integer $idville
 * @property string $adresse
 * @property string $tel1
 * @property string $tel2
 * @property string $fax
 * @property integer $active
 * @property CarVille $CarVille
 * @property CarGar $CarGar
 * 
 * @method integer       getIdadressegar() Returns the current record's "idadressegar" value
 * @method integer       getIdgar()        Returns the current record's "idgar" value
 * @method integer       getIdville()      Returns the current record's "idville" value
 * @method string        getAdresse()      Returns the current record's "adresse" value
 * @method string        getTel1()         Returns the current record's "tel1" value
 * @method string        getTel2()         Returns the current record's "tel2" value
 * @method string        getFax()          Returns the current record's "fax" value
 * @method integer       getActive()       Returns the current record's "active" value
 * @method CarVille      getCarVille()     Returns the current record's "CarVille" value
 * @method CarGar        getCarGar()       Returns the current record's "CarGar" value
 * @method CarAdresseGar setIdadressegar() Sets the current record's "idadressegar" value
 * @method CarAdresseGar setIdgar()        Sets the current record's "idgar" value
 * @method CarAdresseGar setIdville()      Sets the current record's "idville" value
 * @method CarAdresseGar setAdresse()      Sets the current record's "adresse" value
 * @method CarAdresseGar setTel1()         Sets the current record's "tel1" value
 * @method CarAdresseGar setTel2()         Sets the current record's "tel2" value
 * @method CarAdresseGar setFax()          Sets the current record's "fax" value
 * @method CarAdresseGar setActive()       Sets the current record's "active" value
 * @method CarAdresseGar setCarVille()     Sets the current record's "CarVille" value
 * @method CarAdresseGar setCarGar()       Sets the current record's "CarGar" value
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarAdresseGar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_adress_gar');
        $this->hasColumn('idadressegar', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('idgar', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('idville', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('adresse', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tel1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tel2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('fax', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CarVille', array(
             'local' => 'idville',
             'foreign' => 'idville'));

        $this->hasOne('CarGar', array(
             'local' => 'idgar',
             'foreign' => 'idgar',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}