<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarMarque', 'doctrine');

/**
 * BaseCarMarque
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmarque
 * @property string $title
 * @property string $image
 * @property string $imagelittle
 * @property string $information
 * @property string $description
 * @property integer $notevisiteur
 * @property integer $nbnotevisiteur
 * @property integer $noteadmin
 * @property integer $nbnoteadmin
 * @property integer $active
 * @property Doctrine_Collection $CarModele
 * @property Doctrine_Collection $CarCon
 * @property Doctrine_Collection $CarAuto
 * 
 * @method integer             getIdmarque()       Returns the current record's "idmarque" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method string              getImage()          Returns the current record's "image" value
 * @method string              getImagelittle()    Returns the current record's "imagelittle" value
 * @method string              getInformation()    Returns the current record's "information" value
 * @method string              getDescription()    Returns the current record's "description" value
 * @method integer             getNotevisiteur()   Returns the current record's "notevisiteur" value
 * @method integer             getNbnotevisiteur() Returns the current record's "nbnotevisiteur" value
 * @method integer             getNoteadmin()      Returns the current record's "noteadmin" value
 * @method integer             getNbnoteadmin()    Returns the current record's "nbnoteadmin" value
 * @method integer             getActive()         Returns the current record's "active" value
 * @method Doctrine_Collection getCarModele()      Returns the current record's "CarModele" collection
 * @method Doctrine_Collection getCarCon()         Returns the current record's "CarCon" collection
 * @method Doctrine_Collection getCarAuto()        Returns the current record's "CarAuto" collection
 * @method CarMarque           setIdmarque()       Sets the current record's "idmarque" value
 * @method CarMarque           setTitle()          Sets the current record's "title" value
 * @method CarMarque           setImage()          Sets the current record's "image" value
 * @method CarMarque           setImagelittle()    Sets the current record's "imagelittle" value
 * @method CarMarque           setInformation()    Sets the current record's "information" value
 * @method CarMarque           setDescription()    Sets the current record's "description" value
 * @method CarMarque           setNotevisiteur()   Sets the current record's "notevisiteur" value
 * @method CarMarque           setNbnotevisiteur() Sets the current record's "nbnotevisiteur" value
 * @method CarMarque           setNoteadmin()      Sets the current record's "noteadmin" value
 * @method CarMarque           setNbnoteadmin()    Sets the current record's "nbnoteadmin" value
 * @method CarMarque           setActive()         Sets the current record's "active" value
 * @method CarMarque           setCarModele()      Sets the current record's "CarModele" collection
 * @method CarMarque           setCarCon()         Sets the current record's "CarCon" collection
 * @method CarMarque           setCarAuto()        Sets the current record's "CarAuto" collection
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarMarque extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_marque');
        $this->hasColumn('idmarque', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('image', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imagelittle', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('information', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('notevisiteur', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('nbnotevisiteur', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('noteadmin', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('nbnoteadmin', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CarModele', array(
             'local' => 'idmarque',
             'foreign' => 'idmarque'));

        $this->hasMany('CarCon', array(
             'local' => 'idmarque',
             'foreign' => 'idmarque'));

        $this->hasMany('CarAuto', array(
             'local' => 'idmarque',
             'foreign' => 'idmarque'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}