<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarMessage', 'doctrine');

/**
 * BaseCarMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmessage
 * @property integer $iduserfrom
 * @property integer $iduserto
 * @property string $commentaire
 * @property integer $active
 * 
 * @method integer    getIdmessage()   Returns the current record's "idmessage" value
 * @method integer    getIduserfrom()  Returns the current record's "iduserfrom" value
 * @method integer    getIduserto()    Returns the current record's "iduserto" value
 * @method string     getCommentaire() Returns the current record's "commentaire" value
 * @method integer    getActive()      Returns the current record's "active" value
 * @method CarMessage setIdmessage()   Sets the current record's "idmessage" value
 * @method CarMessage setIduserfrom()  Sets the current record's "iduserfrom" value
 * @method CarMessage setIduserto()    Sets the current record's "iduserto" value
 * @method CarMessage setCommentaire() Sets the current record's "commentaire" value
 * @method CarMessage setActive()      Sets the current record's "active" value
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_message');
        $this->hasColumn('idmessage', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('iduserfrom', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('iduserto', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('commentaire', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}