<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarAccessoires', 'doctrine');

/**
 * BaseCarAccessoires
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idacc
 * @property integer $idauto
 * @property integer $active
 * @property CarAuto $CarAuto
 * @property CarAccessoire $CarAccessoire
 * 
 * @method integer        getIdacc()         Returns the current record's "idacc" value
 * @method integer        getIdauto()        Returns the current record's "idauto" value
 * @method integer        getActive()        Returns the current record's "active" value
 * @method CarAuto        getCarAuto()       Returns the current record's "CarAuto" value
 * @method CarAccessoire  getCarAccessoire() Returns the current record's "CarAccessoire" value
 * @method CarAccessoires setIdacc()         Sets the current record's "idacc" value
 * @method CarAccessoires setIdauto()        Sets the current record's "idauto" value
 * @method CarAccessoires setActive()        Sets the current record's "active" value
 * @method CarAccessoires setCarAuto()       Sets the current record's "CarAuto" value
 * @method CarAccessoires setCarAccessoire() Sets the current record's "CarAccessoire" value
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarAccessoires extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_accessoires');
        $this->hasColumn('idacc', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('idauto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CarAuto', array(
             'local' => 'idauto',
             'foreign' => 'idauto',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CarAccessoire', array(
             'local' => 'idacc',
             'foreign' => 'idacc',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}