<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarPrestations', 'doctrine');

/**
 * BaseCarPrestations
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idprestation
 * @property integer $idgroup
 * @property integer $iduser
 * @property integer $prix
 * @property integer $active
 * @property CarPrestation $CarPrestation
 * 
 * @method integer        getIdprestation()  Returns the current record's "idprestation" value
 * @method integer        getIdgroup()       Returns the current record's "idgroup" value
 * @method integer        getIduser()        Returns the current record's "iduser" value
 * @method integer        getPrix()          Returns the current record's "prix" value
 * @method integer        getActive()        Returns the current record's "active" value
 * @method CarPrestation  getCarPrestation() Returns the current record's "CarPrestation" value
 * @method CarPrestations setIdprestation()  Sets the current record's "idprestation" value
 * @method CarPrestations setIdgroup()       Sets the current record's "idgroup" value
 * @method CarPrestations setIduser()        Sets the current record's "iduser" value
 * @method CarPrestations setPrix()          Sets the current record's "prix" value
 * @method CarPrestations setActive()        Sets the current record's "active" value
 * @method CarPrestations setCarPrestation() Sets the current record's "CarPrestation" value
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarPrestations extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_prestations');
        $this->hasColumn('idprestation', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('idgroup', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('iduser', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('prix', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CarPrestation', array(
             'local' => 'idprestation',
             'foreign' => 'idprestation',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}