<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarCreneauProposition', 'doctrine');

/**
 * BaseCarCreneauProposition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcrenauprop
 * @property integer $idauto
 * @property integer $iduser
 * @property string $commentaire
 * @property integer $active
 * @property CarAuto $CarAuto
 * 
 * @method integer               getIdcrenauprop() Returns the current record's "idcrenauprop" value
 * @method integer               getIdauto()       Returns the current record's "idauto" value
 * @method integer               getIduser()       Returns the current record's "iduser" value
 * @method string                getCommentaire()  Returns the current record's "commentaire" value
 * @method integer               getActive()       Returns the current record's "active" value
 * @method CarAuto               getCarAuto()      Returns the current record's "CarAuto" value
 * @method CarCreneauProposition setIdcrenauprop() Sets the current record's "idcrenauprop" value
 * @method CarCreneauProposition setIdauto()       Sets the current record's "idauto" value
 * @method CarCreneauProposition setIduser()       Sets the current record's "iduser" value
 * @method CarCreneauProposition setCommentaire()  Sets the current record's "commentaire" value
 * @method CarCreneauProposition setActive()       Sets the current record's "active" value
 * @method CarCreneauProposition setCarAuto()      Sets the current record's "CarAuto" value
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarCreneauProposition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_creneauprop');
        $this->hasColumn('idcrenauprop', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('idauto', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('iduser', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('commentaire', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CarAuto', array(
             'local' => 'idauto',
             'foreign' => 'idauto',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}