<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarCouleur', 'doctrine');

/**
 * BaseCarCouleur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcouleur
 * @property string $title
 * @property string $hexrep
 * @property string $image
 * @property integer $active
 * @property Doctrine_Collection $CarAuto
 * 
 * @method integer             getIdcouleur() Returns the current record's "idcouleur" value
 * @method string              getTitle()     Returns the current record's "title" value
 * @method string              getHexrep()    Returns the current record's "hexrep" value
 * @method string              getImage()     Returns the current record's "image" value
 * @method integer             getActive()    Returns the current record's "active" value
 * @method Doctrine_Collection getCarAuto()   Returns the current record's "CarAuto" collection
 * @method CarCouleur          setIdcouleur() Sets the current record's "idcouleur" value
 * @method CarCouleur          setTitle()     Sets the current record's "title" value
 * @method CarCouleur          setHexrep()    Sets the current record's "hexrep" value
 * @method CarCouleur          setImage()     Sets the current record's "image" value
 * @method CarCouleur          setActive()    Sets the current record's "active" value
 * @method CarCouleur          setCarAuto()   Sets the current record's "CarAuto" collection
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarCouleur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_couleur');
        $this->hasColumn('idcouleur', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('hexrep', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '8',
             ));
        $this->hasColumn('image', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CarAuto', array(
             'local' => 'idcouleur',
             'foreign' => 'idcouleur'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}