<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarImages', 'doctrine');

/**
 * BaseCarImages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idimage
 * @property integer $idauto
 * @property CarImage $CarImage
 * @property CarAuto $CarAuto
 * 
 * @method integer   getIdimage()  Returns the current record's "idimage" value
 * @method integer   getIdauto()   Returns the current record's "idauto" value
 * @method CarImage  getCarImage() Returns the current record's "CarImage" value
 * @method CarAuto   getCarAuto()  Returns the current record's "CarAuto" value
 * @method CarImages setIdimage()  Sets the current record's "idimage" value
 * @method CarImages setIdauto()   Sets the current record's "idauto" value
 * @method CarImages setCarImage() Sets the current record's "CarImage" value
 * @method CarImages setCarAuto()  Sets the current record's "CarAuto" value
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarImages extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_images');
        $this->hasColumn('idimage', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('idauto', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '10',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CarImage', array(
             'local' => 'idimage',
             'foreign' => 'idimage',
             'onDelete' => 'CASCADE'));

        $this->hasOne('CarAuto', array(
             'local' => 'idauto',
             'foreign' => 'idauto',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}