<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarPays', 'doctrine');

/**
 * BaseCarPays
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idpays
 * @property string $title
 * @property string $devise
 * @property string $code
 * @property string $bigcode
 * @property integer $active
 * @property Doctrine_Collection $CarVille
 * @property Doctrine_Collection $CarAuto
 * 
 * @method integer             getIdpays()   Returns the current record's "idpays" value
 * @method string              getTitle()    Returns the current record's "title" value
 * @method string              getDevise()   Returns the current record's "devise" value
 * @method string              getCode()     Returns the current record's "code" value
 * @method string              getBigcode()  Returns the current record's "bigcode" value
 * @method integer             getActive()   Returns the current record's "active" value
 * @method Doctrine_Collection getCarVille() Returns the current record's "CarVille" collection
 * @method Doctrine_Collection getCarAuto()  Returns the current record's "CarAuto" collection
 * @method CarPays             setIdpays()   Sets the current record's "idpays" value
 * @method CarPays             setTitle()    Sets the current record's "title" value
 * @method CarPays             setDevise()   Sets the current record's "devise" value
 * @method CarPays             setCode()     Sets the current record's "code" value
 * @method CarPays             setBigcode()  Sets the current record's "bigcode" value
 * @method CarPays             setActive()   Sets the current record's "active" value
 * @method CarPays             setCarVille() Sets the current record's "CarVille" collection
 * @method CarPays             setCarAuto()  Sets the current record's "CarAuto" collection
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarPays extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_pays');
        $this->hasColumn('idpays', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('devise', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('code', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('bigcode', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '3',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CarVille', array(
             'local' => 'idpays',
             'foreign' => 'idpays'));

        $this->hasMany('CarAuto', array(
             'local' => 'idpays',
             'foreign' => 'idpays'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}