<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarAccessoire', 'doctrine');

/**
 * BaseCarAccessoire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idacc
 * @property integer $idtypeacc
 * @property string $title
 * @property string $description
 * @property integer $active
 * @property CarTypeAccessoire $CarTypeAccessoire
 * @property Doctrine_Collection $CarAccessoires
 * 
 * @method integer             getIdacc()             Returns the current record's "idacc" value
 * @method integer             getIdtypeacc()         Returns the current record's "idtypeacc" value
 * @method string              getTitle()             Returns the current record's "title" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method integer             getActive()            Returns the current record's "active" value
 * @method CarTypeAccessoire   getCarTypeAccessoire() Returns the current record's "CarTypeAccessoire" value
 * @method Doctrine_Collection getCarAccessoires()    Returns the current record's "CarAccessoires" collection
 * @method CarAccessoire       setIdacc()             Sets the current record's "idacc" value
 * @method CarAccessoire       setIdtypeacc()         Sets the current record's "idtypeacc" value
 * @method CarAccessoire       setTitle()             Sets the current record's "title" value
 * @method CarAccessoire       setDescription()       Sets the current record's "description" value
 * @method CarAccessoire       setActive()            Sets the current record's "active" value
 * @method CarAccessoire       setCarTypeAccessoire() Sets the current record's "CarTypeAccessoire" value
 * @method CarAccessoire       setCarAccessoires()    Sets the current record's "CarAccessoires" collection
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarAccessoire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_accessoire');
        $this->hasColumn('idacc', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('idtypeacc', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CarTypeAccessoire', array(
             'local' => 'idtypeacc',
             'foreign' => 'idtypeacc'));

        $this->hasMany('CarAccessoires', array(
             'local' => 'idacc',
             'foreign' => 'idacc'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}