<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarAccessoireExt', 'doctrine');

/**
 * BaseCarAccessoireExt
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idacc
 * @property integer $idauto
 * @property string $title
 * @property integer $active
 * @property CarAuto $CarAuto
 * 
 * @method integer          getIdacc()   Returns the current record's "idacc" value
 * @method integer          getIdauto()  Returns the current record's "idauto" value
 * @method string           getTitle()   Returns the current record's "title" value
 * @method integer          getActive()  Returns the current record's "active" value
 * @method CarAuto          getCarAuto() Returns the current record's "CarAuto" value
 * @method CarAccessoireExt setIdacc()   Sets the current record's "idacc" value
 * @method CarAccessoireExt setIdauto()  Sets the current record's "idauto" value
 * @method CarAccessoireExt setTitle()   Sets the current record's "title" value
 * @method CarAccessoireExt setActive()  Sets the current record's "active" value
 * @method CarAccessoireExt setCarAuto() Sets the current record's "CarAuto" value
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarAccessoireExt extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_accessoire_ext');
        $this->hasColumn('idacc', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('idauto', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CarAuto', array(
             'local' => 'idauto',
             'foreign' => 'idauto',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}