<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarAdresseLoc', 'doctrine');

/**
 * BaseCarAdresseLoc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idadresseloc
 * @property integer $idloc
 * @property integer $idville
 * @property string $adresse
 * @property string $tel1
 * @property string $tel2
 * @property string $fax
 * @property integer $active
 * @property CarVille $CarVille
 * @property CarLoc $CarLoc
 * 
 * @method integer       getIdadresseloc() Returns the current record's "idadresseloc" value
 * @method integer       getIdloc()        Returns the current record's "idloc" value
 * @method integer       getIdville()      Returns the current record's "idville" value
 * @method string        getAdresse()      Returns the current record's "adresse" value
 * @method string        getTel1()         Returns the current record's "tel1" value
 * @method string        getTel2()         Returns the current record's "tel2" value
 * @method string        getFax()          Returns the current record's "fax" value
 * @method integer       getActive()       Returns the current record's "active" value
 * @method CarVille      getCarVille()     Returns the current record's "CarVille" value
 * @method CarLoc        getCarLoc()       Returns the current record's "CarLoc" value
 * @method CarAdresseLoc setIdadresseloc() Sets the current record's "idadresseloc" value
 * @method CarAdresseLoc setIdloc()        Sets the current record's "idloc" value
 * @method CarAdresseLoc setIdville()      Sets the current record's "idville" value
 * @method CarAdresseLoc setAdresse()      Sets the current record's "adresse" value
 * @method CarAdresseLoc setTel1()         Sets the current record's "tel1" value
 * @method CarAdresseLoc setTel2()         Sets the current record's "tel2" value
 * @method CarAdresseLoc setFax()          Sets the current record's "fax" value
 * @method CarAdresseLoc setActive()       Sets the current record's "active" value
 * @method CarAdresseLoc setCarVille()     Sets the current record's "CarVille" value
 * @method CarAdresseLoc setCarLoc()       Sets the current record's "CarLoc" value
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarAdresseLoc extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_adress_loc');
        $this->hasColumn('idadresseloc', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('idloc', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('idville', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '10',
             ));
        $this->hasColumn('adresse', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tel1', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tel2', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('fax', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CarVille', array(
             'local' => 'idville',
             'foreign' => 'idville'));

        $this->hasOne('CarLoc', array(
             'local' => 'idloc',
             'foreign' => 'idloc',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}