<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CarGar', 'doctrine');

/**
 * BaseCarGar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idgar
 * @property string $title
 * @property string $information
 * @property string $description
 * @property integer $notevisiteur
 * @property integer $nbnotevisiteur
 * @property integer $noteadmin
 * @property integer $nbnoteadmin
 * @property integer $active
 * @property Doctrine_Collection $CarAdresseGar
 * 
 * @method integer             getIdgar()          Returns the current record's "idgar" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method string              getInformation()    Returns the current record's "information" value
 * @method string              getDescription()    Returns the current record's "description" value
 * @method integer             getNotevisiteur()   Returns the current record's "notevisiteur" value
 * @method integer             getNbnotevisiteur() Returns the current record's "nbnotevisiteur" value
 * @method integer             getNoteadmin()      Returns the current record's "noteadmin" value
 * @method integer             getNbnoteadmin()    Returns the current record's "nbnoteadmin" value
 * @method integer             getActive()         Returns the current record's "active" value
 * @method Doctrine_Collection getCarAdresseGar()  Returns the current record's "CarAdresseGar" collection
 * @method CarGar              setIdgar()          Sets the current record's "idgar" value
 * @method CarGar              setTitle()          Sets the current record's "title" value
 * @method CarGar              setInformation()    Sets the current record's "information" value
 * @method CarGar              setDescription()    Sets the current record's "description" value
 * @method CarGar              setNotevisiteur()   Sets the current record's "notevisiteur" value
 * @method CarGar              setNbnotevisiteur() Sets the current record's "nbnotevisiteur" value
 * @method CarGar              setNoteadmin()      Sets the current record's "noteadmin" value
 * @method CarGar              setNbnoteadmin()    Sets the current record's "nbnoteadmin" value
 * @method CarGar              setActive()         Sets the current record's "active" value
 * @method CarGar              setCarAdresseGar()  Sets the current record's "CarAdresseGar" collection
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCarGar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('car_gar');
        $this->hasColumn('idgar', 'integer', 10, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('information', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('notevisiteur', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('nbnotevisiteur', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('noteadmin', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('nbnoteadmin', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '2',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CarAdresseGar', array(
             'local' => 'idgar',
             'foreign' => 'idgar'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}