Contacts:
  connection: doctrine
  tableName: contacts
  columns:
    user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    contact:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
Emoticones:
  connection: doctrine
  tableName: emoticones
  columns:
    idemoticones:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    racourci:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    image:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Priorite:
  connection: doctrine
  tableName: priorite
  columns:
    idpriorite:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    libelle:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Request:
      local: idpriorite
      foreign: priorite
      type: many
Request:
  connection: doctrine
  tableName: request
  columns:
    idrequest:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    content:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    priorite:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    type:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    title:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Priorite:
      local: priorite
      foreign: idpriorite
      type: one
    Type:
      local: type
      foreign: idtype
      type: one
    User:
      local: user
      foreign: iduser
      type: one
    Response:
      local: idrequest
      foreign: request
      type: many
Requestusers:
  connection: doctrine
  tableName: requestusers
  columns:
    request:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    readed:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Response:
  connection: doctrine
  tableName: response
  columns:
    idresponse:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    content:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    request:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    response:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Request:
      local: request
      foreign: idrequest
      type: one
    Response:
      local: idresponse
      foreign: response
      type: many
    User:
      local: user
      foreign: iduser
      type: one
Subscribe:
  connection: doctrine
  tableName: subscribe
  columns:
    user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    type:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    dateinscr:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Type:
  connection: doctrine
  tableName: type
  columns:
    idtype:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    libelle:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Request:
      local: idtype
      foreign: type
      type: many
User:
  connection: doctrine
  tableName: user
  columns:
    email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nom:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    prenom:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    pseudo:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    adr:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tel:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    etudiant:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    salarie:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    statut:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    entreprise:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    niveauetude:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ecole:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    iduser:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
  relations:
    Request:
      local: iduser
      foreign: user
      type: many
    Response:
      local: iduser
      foreign: user
      type: many
