<?php

/**
 * AmjiUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class AmjiUser extends BaseAmjiUser
{
	public static function userIsExist($login) {
		$getUsernameUser = Doctrine_Query::create ()->select ( 'u.email' )->from ( 'AmjiUser u' )->where ( "email = '" . $login . "'" )->execute ();
		$oldUsername = $getUsernameUser [0];

		if ($oldUsername->getEmail () != NULL)
			return 1;
		else
			return 0;
	}

	public static function createUser(CreateUserVO $uservo){
		
		
			if(!AmjiUser::userIsExist($uservo->email)){
				$user = new sfGuardUser ( );
				$user->setPassword ( $uservo->password );
				$user->setUsername ( $uservo->email );
				
				$user->save ();
				
				$compte = new AmjiUser();
				$compte->setEmail($uservo->email);
				$compte->setNom($uservo->nom);
				$compte->setPrenom($uservo->prenom);
				$compte->setPseudo($uservo->pseudo);
				$compte->setAdr($uservo->adr);
				$compte->setTel($uservo->tel);
				$compte->setEtudiant($uservo->etudiant);
				$compte->setEcole($uservo->ecole);
				$compte->setNiveau($uservo->niveau);
				$compte->setStatut($uservo->statut);
				$compte->setSalarie($uservo->salarie);
				$compte->setSociete($uservo->societe);
				
				$compte->save();
				 
			}else{
				throw new GenericException("",Errors::MAILEXIST);
			}
				
		
	}
	
	public static function addContact($iduser,$idcontact){
		
	}
}