<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/11/29 13:23:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=car',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
