<?php

/**
 * AmjiType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class AmjiType extends BaseAmjiType
{
	public static function getAllType(){
		$types = Doctrine_Query::create ()->from ( 'AmjiType t' )->where('t.active = 1')->execute();
		return $types;
	}
	
	public static function getTypePerUser($iduser){
		$types = Doctrine_Query::create ()->from ( 'AmjiType t' )->leftJoin('t.AmjiSubscribe s')->where('s.idamji_user = '.$iduser)->execute();
		return $types;
	}
}