<?php

/**
 * AmjiStatut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class AmjiStatut extends BaseAmjiStatut
{
	public static function getStatutId($statut) {


		$statuts = Doctrine_Query::create ()->from ( 'AmjiStatut u' )->where ( "u.libelle = '" . $statut . "'" )->execute ();
		
		return $statuts[0]->getIdamji_statut();
	}	
	
	public static function getStatutById($idstatut) {


		$statuts = Doctrine_Query::create ()->from ( 'AmjiStatut u' )->where ( "u.idamji_statut = " . $idstatut )->execute ();
		
		return $statuts[0]->getLibelle();
	}	
}