<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiSubscribeGroup', 'doctrine');

/**
 * BaseAmjiSubscribeGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_user
 * @property integer $idamji_group
 * @property AmjiUser $AmjiUser
 * @property AmjiGroup $AmjiGroup
 * 
 * @method integer            getIdamjiUser()   Returns the current record's "idamji_user" value
 * @method integer            getIdamjiGroup()  Returns the current record's "idamji_group" value
 * @method AmjiUser           getAmjiUser()     Returns the current record's "AmjiUser" value
 * @method AmjiGroup          getAmjiGroup()    Returns the current record's "AmjiGroup" value
 * @method AmjiSubscribeGroup setIdamjiUser()   Sets the current record's "idamji_user" value
 * @method AmjiSubscribeGroup setIdamjiGroup()  Sets the current record's "idamji_group" value
 * @method AmjiSubscribeGroup setAmjiUser()     Sets the current record's "AmjiUser" value
 * @method AmjiSubscribeGroup setAmjiGroup()    Sets the current record's "AmjiGroup" value
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiSubscribeGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_subscribe_group');
        $this->hasColumn('idamji_user', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('idamji_group', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmjiUser', array(
             'local' => 'idamji_user',
             'foreign' => 'idamji_user'));

        $this->hasOne('AmjiGroup', array(
             'local' => 'idamji_group',
             'foreign' => 'idamji_group'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}