<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiFile', 'doctrine');

/**
 * BaseAmjiFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_file
 * @property blob $content
 * 
 * @method integer  getIdamjiFile()  Returns the current record's "idamji_file" value
 * @method blob     getContent()     Returns the current record's "content" value
 * @method AmjiFile setIdamjiFile()  Sets the current record's "idamji_file" value
 * @method AmjiFile setContent()     Sets the current record's "content" value
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_file');
        $this->hasColumn('idamji_file', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('content', 'blob', null, array(
             'type' => 'blob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}