<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Contacts', 'doctrine');

/**
 * BaseContacts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user
 * @property integer $contact
 * 
 * @method integer  getUser()    Returns the current record's "user" value
 * @method integer  getContact() Returns the current record's "contact" value
 * @method Contacts setUser()    Sets the current record's "user" value
 * @method Contacts setContact() Sets the current record's "contact" value
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseContacts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contacts');
        $this->hasColumn('user', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('contact', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}