<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiTypeEvent', 'doctrine');

/**
 * BaseAmjiTypeEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_type
 * @property string $libelle
 * @property integer $owner
 * @property string $description
 * @property Doctrine_Collection $AmjiUser
 * @property Doctrine_Collection $AmjiEvent
 * 
 * @method integer             getIdamjiType()  Returns the current record's "idamji_type" value
 * @method string              getLibelle()     Returns the current record's "libelle" value
 * @method integer             getOwner()       Returns the current record's "owner" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getAmjiUser()    Returns the current record's "AmjiUser" collection
 * @method Doctrine_Collection getAmjiEvent()   Returns the current record's "AmjiEvent" collection
 * @method AmjiTypeEvent       setIdamjiType()  Sets the current record's "idamji_type" value
 * @method AmjiTypeEvent       setLibelle()     Sets the current record's "libelle" value
 * @method AmjiTypeEvent       setOwner()       Sets the current record's "owner" value
 * @method AmjiTypeEvent       setDescription() Sets the current record's "description" value
 * @method AmjiTypeEvent       setAmjiUser()    Sets the current record's "AmjiUser" collection
 * @method AmjiTypeEvent       setAmjiEvent()   Sets the current record's "AmjiEvent" collection
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiTypeEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_type_event');
        $this->hasColumn('idamji_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('libelle', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '100',
             ));
        $this->hasColumn('owner', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AmjiUser', array(
             'local' => 'owner',
             'foreign' => 'idamji_user'));

        $this->hasMany('AmjiEvent', array(
             'local' => 'idamji_type',
             'foreign' => 'idtype'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}