<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiCastResponse', 'doctrine');

/**
 * BaseAmjiCastResponse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_response
 * @property integer $iduser
 * @property integer $active
 * @property AmjiUser $AmjiUser
 * @property AmjiResponse $AmjiResponse
 * 
 * @method integer          getIdamjiResponse()  Returns the current record's "idamji_response" value
 * @method integer          getIduser()          Returns the current record's "iduser" value
 * @method integer          getActive()          Returns the current record's "active" value
 * @method AmjiUser         getAmjiUser()        Returns the current record's "AmjiUser" value
 * @method AmjiResponse     getAmjiResponse()    Returns the current record's "AmjiResponse" value
 * @method AmjiCastResponse setIdamjiResponse()  Sets the current record's "idamji_response" value
 * @method AmjiCastResponse setIduser()          Sets the current record's "iduser" value
 * @method AmjiCastResponse setActive()          Sets the current record's "active" value
 * @method AmjiCastResponse setAmjiUser()        Sets the current record's "AmjiUser" value
 * @method AmjiCastResponse setAmjiResponse()    Sets the current record's "AmjiResponse" value
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiCastResponse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_cast_response');
        $this->hasColumn('idamji_response', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('iduser', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmjiUser', array(
             'local' => 'iduser',
             'foreign' => 'idamji_user'));

        $this->hasOne('AmjiResponse', array(
             'local' => 'idamji_response',
             'foreign' => 'idamji_response'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}