package commun
{
	import flash.data.EncryptedLocalStore;
	import flash.display.NativeMenu;
	import flash.display.NativeMenuItem;
	import flash.utils.ByteArray;
	
	import mx.collections.ArrayCollection;
	
	public class Commun
	{
		public function Commun()
		{
		}
		
		public static var checkLogin : String = "checkLogin";
		public static var checkPass : String = "checkPass";
		public static var login : String = "login";
		public static var pass : String = "pass";
		
		public static function strreplace( replace_what:String, replace_by:String, original:String ):String
		{
			var array:Array = original.split(replace_what);
			return array.join(replace_by);
		}
		
		public static function storeEncrypt(key : String,value : String):void{
				var bytes : ByteArray = new ByteArray(); 
				bytes.writeUTFBytes(value); 
				EncryptedLocalStore.setItem(key, bytes);				
		}
		
		public static function getStoredItem(key : String):String{
			var bytes : ByteArray = EncryptedLocalStore.getItem(key);
			if(bytes!=null)
				return bytes.readUTFBytes(bytes.length);
			else return null;
		}
		
		public static function clearStoredItem(key : String):void{
			EncryptedLocalStore.removeItem(key);
		}
		
		public static function clearAllStoredItem():void{
			EncryptedLocalStore.reset();
		}
		
		
		public static function addChildrenToMenu(menu:NativeMenu,
                                children:XMLList):NativeMenuItem
        {
            var menuItem:NativeMenuItem;
            var submenu:NativeMenu;
            
            for each (var child:XML in children)
            {
                if (String(child.@label).length > 0)
                {
                    menuItem = new NativeMenuItem(child.@label);
                    menuItem.name = child.name();
                }
                else
                {
                    menuItem = new NativeMenuItem(child.name());
                    menuItem.name = child.name();
                }
                menu.addItem(menuItem);
                if (child.children().length() > 0)
                {
                    menuItem.submenu = new NativeMenu();
                    addChildrenToMenu(menuItem.submenu,child.children());
                }
            }
            return menuItem;
        }
        
        public static function getDomainFromMail(email : String):String{
        	var a : Number = email.substr(0,email.indexOf("@")).length;
        	var b : Number = email.substr(0,email.lastIndexOf(".")).length;
        	return email.substr(email.indexOf("@")+1,b-a-1);        	
        }
        
        public static function getJidFromMail(email : String):String{
        	var a : Number = email.substr(0,email.indexOf("@")).length;
        	var b : Number = email.substr(0,email.lastIndexOf(".")).length;
        	return Constantes.XMPPUSERPREFIX+email.substr(0,email.lastIndexOf("@"))+email.substr(email.indexOf("@")+1,b-a-1);        	
        }
        
        public static var emoticones:ArrayCollection = new ArrayCollection([
			{link:":d", glink:"", source:""},			
		]);
		
		public static var globalemoticones : ArrayCollection = new ArrayCollection([
			{glink : '' , source : "assets/emoticones/2s/24/anger.png"},
			{glink : '' , source : "assets/emoticones/2s/24/burn.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/confused.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/cool.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/cry.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/fire.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/grimace.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_angry.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_confused.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_cool.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_cry.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_eek.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_fd.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_ft.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_heart.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_lol.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_lovely.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_music.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_question.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_razz.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_sad.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_shame.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_shuai.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_sleep.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_smile.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_sweat.png"},
			{glink : '' , source : "assets/emoticones/2s/24/icon_tong.png"},
			{glink : '' , source : "assets/emoticones/2s/24/love.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/miao.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/prettiness.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/question.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/shout.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/slobber.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/smile.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/spook.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/startle.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/surprise.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/sweat.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/thirst.PNG"},
			{glink : '' , source : "assets/emoticones/2s/24/vomit.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/anger.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/burn.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/confused.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/cool.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/cry.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/fire.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/grimace.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_angry.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_confused.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_cool.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_cry.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_eek.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_fd.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_ft.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_heart.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_lol.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_lovely.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_music.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_question.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_razz.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_sad.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_shame.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_shuai.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_sleep.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_smile.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_sweat.png"},
			{glink : '' , source : "assets/emoticones/2s/32/icon_tong.png"},
			{glink : '' , source : "assets/emoticones/2s/32/love.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/miao.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/prettiness.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/question.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/shout.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/slobber.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/smile.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/spook.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/startle.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/surprise.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/sweat.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/thirst.PNG"},
			{glink : '' , source : "assets/emoticones/2s/32/vomit.PNG"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (1).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (10).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (11).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (12).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (13).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (14).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (15).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (16).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (17).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (18).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (19).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (2).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (20).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (21).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (22).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (23).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (24).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (25).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (26).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (27).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (28).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (29).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (3).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (30).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (31).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (32).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (33).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (34).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (35).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (36).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (37).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (38).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (39).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (4).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (5).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (6).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (7).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (8).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32 (9).png"},
			{glink : '' , source : "assets/emoticones/blue/24/32.png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (1).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (10).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (11).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (12).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (13).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (14).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (15).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (16).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (17).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (18).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (19).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (2).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (20).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (21).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (22).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (23).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (24).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (25).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (26).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (27).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (28).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (29).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (3).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (30).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (31).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (32).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (33).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (34).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (35).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (36).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (37).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (38).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (39).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (4).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (5).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (6).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (7).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (8).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32 (9).png"},
			{glink : '' , source : "assets/emoticones/blue/32/32.png"},
			{glink : '' , source : "assets/emoticones/jambo/act-up.png"},
			{glink : '' , source : "assets/emoticones/jambo/airplane.png"},
			{glink : '' , source : "assets/emoticones/jambo/alien.png"},
			{glink : '' , source : "assets/emoticones/jambo/angel.png"},
			{glink : '' , source : "assets/emoticones/jambo/angry.png"},
			{glink : '' , source : "assets/emoticones/jambo/arrogant.png"},
			{glink : '' , source : "assets/emoticones/jambo/at-wits-end.png"},
			{glink : '' , source : "assets/emoticones/jambo/bad.png"},
			{glink : '' , source : "assets/emoticones/jambo/bashful.png"},
			{glink : '' , source : "assets/emoticones/jambo/beat-up.png"},
			{glink : '' , source : "assets/emoticones/jambo/beauty.png"},
			{glink : '' , source : "assets/emoticones/jambo/beer.png"},
			{glink : '' , source : "assets/emoticones/jambo/blowkiss.png"},
			{glink : '' , source : "assets/emoticones/jambo/bomb.png"},
			{glink : '' , source : "assets/emoticones/jambo/bowl.png"},
			{glink : '' , source : "assets/emoticones/jambo/boy.png"},
			{glink : '' , source : "assets/emoticones/jambo/brb.png"},
			{glink : '' , source : "assets/emoticones/jambo/bulgy-eyes.png"},
			{glink : '' , source : "assets/emoticones/jambo/bunny.png"},
			{glink : '' , source : "assets/emoticones/jambo/bye.png"},
			{glink : '' , source : "assets/emoticones/jambo/cake.png"},
			{glink : '' , source : "assets/emoticones/jambo/call-me.png"},
			{glink : '' , source : "assets/emoticones/jambo/camera.png"},
			{glink : '' , source : "assets/emoticones/jambo/can.png"},
			{glink : '' , source : "assets/emoticones/jambo/car.png"},
			{glink : '' , source : "assets/emoticones/jambo/cash.png"},
			{glink : '' , source : "assets/emoticones/jambo/cat.png"},
			{glink : '' , source : "assets/emoticones/jambo/chicken.png"},
			{glink : '' , source : "assets/emoticones/jambo/cigarette.png"},
			{glink : '' , source : "assets/emoticones/jambo/clap.png"},
			{glink : '' , source : "assets/emoticones/jambo/clock.png"},
			{glink : '' , source : "assets/emoticones/jambo/cloudy.png"},
			{glink : '' , source : "assets/emoticones/jambo/clover.png"},
			{glink : '' , source : "assets/emoticones/jambo/clown.png"},
			{glink : '' , source : "assets/emoticones/jambo/coffee.png"},
			{glink : '' , source : "assets/emoticones/jambo/coins.png"},
			{glink : '' , source : "assets/emoticones/jambo/computer.png"},
			{glink : '' , source : "assets/emoticones/jambo/confused.png"},
			{glink : '' , source : "assets/emoticones/jambo/console.png"},
			{glink : '' , source : "assets/emoticones/jambo/cow.png"},
			{glink : '' , source : "assets/emoticones/jambo/cowbell.png"},
			{glink : '' , source : "assets/emoticones/jambo/cowboy.png"},
			{glink : '' , source : "assets/emoticones/jambo/crying.png"},
			{glink : '' , source : "assets/emoticones/jambo/curl-lip.png"},
			{glink : '' , source : "assets/emoticones/jambo/curse.png"},
			{glink : '' , source : "assets/emoticones/jambo/cute.png"},
			{glink : '' , source : "assets/emoticones/jambo/cyclops.png"},
			{glink : '' , source : "assets/emoticones/jambo/dance.png"},
			{glink : '' , source : "assets/emoticones/jambo/dazed.png"},
			{glink : '' , source : "assets/emoticones/jambo/desire.png"},
			{glink : '' , source : "assets/emoticones/jambo/devil.png"},
			{glink : '' , source : "assets/emoticones/jambo/disapointed.png"},
			{glink : '' , source : "assets/emoticones/jambo/disdain.png"},
			{glink : '' , source : "assets/emoticones/jambo/doctor.png"},
			{glink : '' , source : "assets/emoticones/jambo/dog.png"},
			{glink : '' , source : "assets/emoticones/jambo/doh.png"},
			{glink : '' , source : "assets/emoticones/jambo/dont-know.png"},
			{glink : '' , source : "assets/emoticones/jambo/drink.png"},
			{glink : '' , source : "assets/emoticones/jambo/drool.png"},
			{glink : '' , source : "assets/emoticones/jambo/eat.png"},
			{glink : '' , source : "assets/emoticones/jambo/embarrassed.png"},
			{glink : '' , source : "assets/emoticones/jambo/emblem-favorites.png"},
			{glink : '' , source : "assets/emoticones/jambo/emo.png"},
			{glink : '' , source : "assets/emoticones/jambo/excruciating.png"},
			{glink : '' , source : "assets/emoticones/jambo/eyeroll.png"},
			{glink : '' , source : "assets/emoticones/jambo/female-fighter.png"},
			{glink : '' , source : "assets/emoticones/jambo/female.png"},
			{glink : '' , source : "assets/emoticones/jambo/film.png"},
			{glink : '' , source : "assets/emoticones/jambo/fingers-crossed.png"},
			{glink : '' , source : "assets/emoticones/jambo/flag.png"},
			{glink : '' , source : "assets/emoticones/jambo/foot-in-mouth.png"},
			{glink : '' , source : "assets/emoticones/jambo/freaked-out.png"},
			{glink : '' , source : "assets/emoticones/jambo/ghost.png"},
			{glink : '' , source : "assets/emoticones/jambo/giggle.png"},
			{glink : '' , source : "assets/emoticones/jambo/girl.png"},
			{glink : '' , source : "assets/emoticones/jambo/glasses-cool.png"},
			{glink : '' , source : "assets/emoticones/jambo/glasses-nerdy.png"},
			{glink : '' , source : "assets/emoticones/jambo/go-away.png"},
			{glink : '' , source : "assets/emoticones/jambo/goat.png"},
			{glink : '' , source : "assets/emoticones/jambo/good.png"},
			{glink : '' , source : "assets/emoticones/jambo/hammer.png"},
			{glink : '' , source : "assets/emoticones/jambo/handcuffs.png"},
			{glink : '' , source : "assets/emoticones/jambo/handshake.png"},
			{glink : '' , source : "assets/emoticones/jambo/highfive.png"},
			{glink : '' , source : "assets/emoticones/jambo/hug-left.png"},
			{glink : '' , source : "assets/emoticones/jambo/hug-right.png"},
			{glink : '' , source : "assets/emoticones/jambo/hungry.png"},
			{glink : '' , source : "assets/emoticones/jambo/hypnotized.png"},
			{glink : '' , source : "assets/emoticones/jambo/in-love.png"},
			{glink : '' , source : "assets/emoticones/jambo/island.png"},
			{glink : '' , source : "assets/emoticones/jambo/jump.png"},
			{glink : '' , source : "assets/emoticones/jambo/kiss.png"},
			{glink : '' , source : "assets/emoticones/jambo/kissed.png"},
			{glink : '' , source : "assets/emoticones/jambo/kissing.png"},
			{glink : '' , source : "assets/emoticones/jambo/knife.png"},
			{glink : '' , source : "assets/emoticones/jambo/lamp.png"},
			{glink : '' , source : "assets/emoticones/jambo/lashes.png"},
			{glink : '' , source : "assets/emoticones/jambo/laugh.png"},
			{glink : '' , source : "assets/emoticones/jambo/liquor.png"},
			{glink : '' , source : "assets/emoticones/jambo/loser.png"},
			{glink : '' , source : "assets/emoticones/jambo/love-over.png"},
			{glink : '' , source : "assets/emoticones/jambo/love.png"},
			{glink : '' , source : "assets/emoticones/jambo/lying.png"},
			{glink : '' , source : "assets/emoticones/jambo/mad-tongue.png"},
			{glink : '' , source : "assets/emoticones/jambo/mail.png"},
			{glink : '' , source : "assets/emoticones/jambo/male-fighter1.png"},
			{glink : '' , source : "assets/emoticones/jambo/male-fighter2.png"},
			{glink : '' , source : "assets/emoticones/jambo/male.png"},
			{glink : '' , source : "assets/emoticones/jambo/mean.png"},
			{glink : '' , source : "assets/emoticones/jambo/meeting.png"},
			{glink : '' , source : "assets/emoticones/jambo/messed.png"},
			{glink : '' , source : "assets/emoticones/jambo/mobile.png"},
			{glink : '' , source : "assets/emoticones/jambo/mohawk.png"},
			{glink : '' , source : "assets/emoticones/jambo/moneymouth.png"},
			{glink : '' , source : "assets/emoticones/jambo/monkey.png"},
			{glink : '' , source : "assets/emoticones/jambo/moon.png"},
			{glink : '' , source : "assets/emoticones/jambo/msn.png"},
			{glink : '' , source : "assets/emoticones/jambo/music.png"},
			{glink : '' , source : "assets/emoticones/jambo/musical-note.png"},
			{glink : '' , source : "assets/emoticones/jambo/nailbiting.png"},
			{glink : '' , source : "assets/emoticones/jambo/neutral.png"},
			{glink : '' , source : "assets/emoticones/jambo/no.png"},
			{glink : '' , source : "assets/emoticones/jambo/on-the-phone.png"},
			{glink : '' , source : "assets/emoticones/jambo/party.png"},
			{glink : '' , source : "assets/emoticones/jambo/peace.png"},
			{glink : '' , source : "assets/emoticones/jambo/phone.png"},
			{glink : '' , source : "assets/emoticones/jambo/pig.png"},
			{glink : '' , source : "assets/emoticones/jambo/pill.png"},
			{glink : '' , source : "assets/emoticones/jambo/pirate.png"},
			{glink : '' , source : "assets/emoticones/jambo/pissed-off.png"},
			{glink : '' , source : "assets/emoticones/jambo/pizza.png"},
			{glink : '' , source : "assets/emoticones/jambo/plate.png"},
			{glink : '' , source : "assets/emoticones/jambo/poop.png"},
			{glink : '' , source : "assets/emoticones/jambo/pray.png"},
			{glink : '' , source : "assets/emoticones/jambo/present.png"},
			{glink : '' , source : "assets/emoticones/jambo/pumpkin.png"},
			{glink : '' , source : "assets/emoticones/jambo/qq.png"},
			{glink : '' , source : "assets/emoticones/jambo/question.png"},
			{glink : '' , source : "assets/emoticones/jambo/quiet.png"},
			{glink : '' , source : "assets/emoticones/jambo/rain.png"},
			{glink : '' , source : "assets/emoticones/jambo/rainbow.png"},
			{glink : '' , source : "assets/emoticones/jambo/rose-dead.png"},
			{glink : '' , source : "assets/emoticones/jambo/rose.png"},
			{glink : '' , source : "assets/emoticones/jambo/rotfl.png"},
			{glink : '' , source : "assets/emoticones/jambo/sad.png"},
			{glink : '' , source : "assets/emoticones/jambo/sarcastic.png"},
			{glink : '' , source : "assets/emoticones/jambo/scream.png"},
			{glink : '' , source : "assets/emoticones/jambo/search.png"},
			{glink : '' , source : "assets/emoticones/jambo/secret.png"},
			{glink : '' , source : "assets/emoticones/jambo/shame.png"},
			{glink : '' , source : "assets/emoticones/jambo/sheep.png"},
			{glink : '' , source : "assets/emoticones/jambo/shock.png"},
			{glink : '' , source : "assets/emoticones/jambo/shout.png"},
			{glink : '' , source : "assets/emoticones/jambo/shut-mouth.png"},
			{glink : '' , source : "assets/emoticones/jambo/sick.png"},
			{glink : '' , source : "assets/emoticones/jambo/sidefrown.png"},
			{glink : '' , source : "assets/emoticones/jambo/silly.png"},
			{glink : '' , source : "assets/emoticones/jambo/sinister.png"},
			{glink : '' , source : "assets/emoticones/jambo/skeleton.png"},
			{glink : '' , source : "assets/emoticones/jambo/skype.png"},
			{glink : '' , source : "assets/emoticones/jambo/skywalker.png"},
			{glink : '' , source : "assets/emoticones/jambo/sleepy.png"},
			{glink : '' , source : "assets/emoticones/jambo/smile-big.png"},
			{glink : '' , source : "assets/emoticones/jambo/smile.png"},
			{glink : '' , source : "assets/emoticones/jambo/smirk.png"},
			{glink : '' , source : "assets/emoticones/jambo/snail.png"},
			{glink : '' , source : "assets/emoticones/jambo/snicker.png"},
			{glink : '' , source : "assets/emoticones/jambo/snowman.png"},
			{glink : '' , source : "assets/emoticones/jambo/soccerball.png"},
			{glink : '' , source : "assets/emoticones/jambo/soldier.png"},
			{glink : '' , source : "assets/emoticones/jambo/star.png"},
			{glink : '' , source : "assets/emoticones/jambo/starving.png"},
			{glink : '' , source : "assets/emoticones/jambo/stop.png"},
			{glink : '' , source : "assets/emoticones/jambo/struggle.png"},
			{glink : '' , source : "assets/emoticones/jambo/sun.png"},
			{glink : '' , source : "assets/emoticones/jambo/sweat.png"},
			{glink : '' , source : "assets/emoticones/jambo/talktohand.png"},
			{glink : '' , source : "assets/emoticones/jambo/teeth.png"},
			{glink : '' , source : "assets/emoticones/jambo/terror.png"},
			{glink : '' , source : "assets/emoticones/jambo/thinking.png"},
			{glink : '' , source : "assets/emoticones/jambo/thunder.png"},
			{glink : '' , source : "assets/emoticones/jambo/time-out.png"},
			{glink : '' , source : "assets/emoticones/jambo/tongue.png"},
			{glink : '' , source : "assets/emoticones/jambo/tremble.png"},
			{glink : '' , source : "assets/emoticones/jambo/turtle.png"},
			{glink : '' , source : "assets/emoticones/jambo/tv.png"},
			{glink : '' , source : "assets/emoticones/jambo/umbrella.png"},
			{glink : '' , source : "assets/emoticones/jambo/vampire.png"},
			{glink : '' , source : "assets/emoticones/jambo/victory.png"},
			{glink : '' , source : "assets/emoticones/jambo/waiting.png"},
			{glink : '' , source : "assets/emoticones/jambo/watermelon.png"},
			{glink : '' , source : "assets/emoticones/jambo/waving.png"},
			{glink : '' , source : "assets/emoticones/jambo/weep.png"},
			{glink : '' , source : "assets/emoticones/jambo/wilt.png"},
			{glink : '' , source : "assets/emoticones/jambo/wink.png"},
			{glink : '' , source : "assets/emoticones/jambo/worship.png"},
			{glink : '' , source : "assets/emoticones/jambo/yawn.png"},
			{glink : '' , source : "assets/emoticones/jambo/yes.png"},
			{glink : '' , source : "assets/emoticones/jambo/yin-yang.png"},
			{glink : '' , source : "assets/emoticones/shiny/arf.gif"},
			{glink : '' , source : "assets/emoticones/shiny/back.gif"},
			{glink : '' , source : "assets/emoticones/shiny/bof.gif"},
			{glink : '' , source : "assets/emoticones/shiny/boss.gif"},
			{glink : '' , source : "assets/emoticones/shiny/boulet.gif"},
			{glink : '' , source : "assets/emoticones/shiny/cry.gif"},
			{glink : '' , source : "assets/emoticones/shiny/emo.gif"},
			{glink : '' , source : "assets/emoticones/shiny/evil.gif"},
			{glink : '' , source : "assets/emoticones/shiny/funky.gif"},
			{glink : '' , source : "assets/emoticones/shiny/gna.gif"},
			{glink : '' , source : "assets/emoticones/shiny/heart.gif"},
			{glink : '' , source : "assets/emoticones/shiny/jap.gif"},
			{glink : '' , source : "assets/emoticones/shiny/kiss.gif"},
			{glink : '' , source : "assets/emoticones/shiny/lol.gif"},
			{glink : '' , source : "assets/emoticones/shiny/lol2.gif"},
			{glink : '' , source : "assets/emoticones/shiny/manga.gif"},
			{glink : '' , source : "assets/emoticones/shiny/next.gif"},
			{glink : '' , source : "assets/emoticones/shiny/no.gif"},
			{glink : '' , source : "assets/emoticones/shiny/o_o.gif"},
			{glink : '' , source : "assets/emoticones/shiny/rolleyes.gif"},
			{glink : '' , source : "assets/emoticones/shiny/shocked.gif"},
			{glink : '' , source : "assets/emoticones/shiny/sleep.gif"},
			{glink : '' , source : "assets/emoticones/shiny/smile.gif"},
			{glink : '' , source : "assets/emoticones/shiny/stop.gif"},
			{glink : '' , source : "assets/emoticones/shiny/suspens.gif"},
			{glink : '' , source : "assets/emoticones/shiny/tux.gif"},
			{glink : '' , source : "assets/emoticones/shiny/wink.gif"},
			{glink : '' , source : "assets/emoticones/shiny/wow.gif"},
			{glink : '' , source : "assets/emoticones/shiny/xD.gif"},
			{glink : '' , source : "assets/emoticones/shiny/yes.gif"},
			{glink : '' , source : "assets/emoticones/wlm/Airplane.png"},
			{glink : '' , source : "assets/emoticones/wlm/Angel.png"},
			{glink : '' , source : "assets/emoticones/wlm/Angry.png"},
			{glink : '' , source : "assets/emoticones/wlm/Auto.png"},
			{glink : '' , source : "assets/emoticones/wlm/Baring teeth.png"},
			{glink : '' , source : "assets/emoticones/wlm/Be right back.png"},
			{glink : '' , source : "assets/emoticones/wlm/Beer mug.png"},
			{glink : '' , source : "assets/emoticones/wlm/Birthday cake.png"},
			{glink : '' , source : "assets/emoticones/wlm/Black sheep.png"},
			{glink : '' , source : "assets/emoticones/wlm/Bowl.png"},
			{glink : '' , source : "assets/emoticones/wlm/Boy.png"},
			{glink : '' , source : "assets/emoticones/wlm/Broken heart.png"},
			{glink : '' , source : "assets/emoticones/wlm/Bunny face.png"},
			{glink : '' , source : "assets/emoticones/wlm/Burning cigarette.png"},
			{glink : '' , source : "assets/emoticones/wlm/Camera.png"},
			{glink : '' , source : "assets/emoticones/wlm/Cat face.png"},
			{glink : '' , source : "assets/emoticones/wlm/Clock.png"},
			{glink : '' , source : "assets/emoticones/wlm/Coffee cup.png"},
			{glink : '' , source : "assets/emoticones/wlm/Coins.png"},
			{glink : '' , source : "assets/emoticones/wlm/Computer.png"},
			{glink : '' , source : "assets/emoticones/wlm/Confused.png"},
			{glink : '' , source : "assets/emoticones/wlm/Crying.png"},
			{glink : '' , source : "assets/emoticones/wlm/Devil.png"},
			{glink : '' , source : "assets/emoticones/wlm/Disappointed.png"},
			{glink : '' , source : "assets/emoticones/wlm/Dog face.png"},
			{glink : '' , source : "assets/emoticones/wlm/Don't tell anyone.png"},
			{glink : '' , source : "assets/emoticones/wlm/E-Mail.png"},
			{glink : '' , source : "assets/emoticones/wlm/Embarrassed.png"},
			{glink : '' , source : "assets/emoticones/wlm/Filmstrip.png"},
			{glink : '' , source : "assets/emoticones/wlm/Fingers crossing.png"},
			{glink : '' , source : "assets/emoticones/wlm/Gift with a bow.png"},
			{glink : '' , source : "assets/emoticones/wlm/Girl.png"},
			{glink : '' , source : "assets/emoticones/wlm/Goat.png"},
			{glink : '' , source : "assets/emoticones/wlm/Green turtle.png"},
			{glink : '' , source : "assets/emoticones/wlm/Handcuffs.png"},
			{glink : '' , source : "assets/emoticones/wlm/High five.png"},
			{glink : '' , source : "assets/emoticones/wlm/Hot.png"},
			{glink : '' , source : "assets/emoticones/wlm/I don't know.png"},
			{glink : '' , source : "assets/emoticones/wlm/Island with a palm tree.png"},
			{glink : '' , source : "assets/emoticones/wlm/Left hug.png"},
			{glink : '' , source : "assets/emoticones/wlm/Light bulb.png"},
			{glink : '' , source : "assets/emoticones/wlm/Martini glass.png"},
			{glink : '' , source : "assets/emoticones/wlm/Mobile phone.png"},
			{glink : '' , source : "assets/emoticones/wlm/Nerd.png"},
			{glink : '' , source : "assets/emoticones/wlm/Note.png"},
			{glink : '' , source : "assets/emoticones/wlm/Open-mouthed.png"},
			{glink : '' , source : "assets/emoticones/wlm/Party.png"},
			{glink : '' , source : "assets/emoticones/wlm/Pizza.png"},
			{glink : '' , source : "assets/emoticones/wlm/Plate.png"},
			{glink : '' , source : "assets/emoticones/wlm/Rainbow.png"},
			{glink : '' , source : "assets/emoticones/wlm/Red Heart.png"},
			{glink : '' , source : "assets/emoticones/wlm/Red lips.png"},
			{glink : '' , source : "assets/emoticones/wlm/Red rose.png"},
			{glink : '' , source : "assets/emoticones/wlm/remake23.deviantart.com.png"},
			{glink : '' , source : "assets/emoticones/wlm/Right hug.png"},
			{glink : '' , source : "assets/emoticones/wlm/Sad.png"},
			{glink : '' , source : "assets/emoticones/wlm/Sarcastic.png"},
			{glink : '' , source : "assets/emoticones/wlm/Secret telling.png"},
			{glink : '' , source : "assets/emoticones/wlm/Sick.png"},
			{glink : '' , source : "assets/emoticones/wlm/Sleeping half-moon.png"},
			{glink : '' , source : "assets/emoticones/wlm/Sleepy.png"},
			{glink : '' , source : "assets/emoticones/wlm/Smile.png"},
			{glink : '' , source : "assets/emoticones/wlm/Snail.png"},
			{glink : '' , source : "assets/emoticones/wlm/Soccer ball.png"},
			{glink : '' , source : "assets/emoticones/wlm/Star.png"},
			{glink : '' , source : "assets/emoticones/wlm/Storm cloud.png"},
			{glink : '' , source : "assets/emoticones/wlm/Stormy cloud.png"},
			{glink : '' , source : "assets/emoticones/wlm/Sun.png"},
			{glink : '' , source : "assets/emoticones/wlm/Surprised.png"},
			{glink : '' , source : "assets/emoticones/wlm/Telephone receiver.png"},
			{glink : '' , source : "assets/emoticones/wlm/Thinking.png"},
			{glink : '' , source : "assets/emoticones/wlm/Thumbs down.png"},
			{glink : '' , source : "assets/emoticones/wlm/Thumbs up.png"},
			{glink : '' , source : "assets/emoticones/wlm/Tongue out.png"},
			{glink : '' , source : "assets/emoticones/wlm/Umbrella.png"},
			{glink : '' , source : "assets/emoticones/wlm/Vampire bat.png"},
			{glink : '' , source : "assets/emoticones/wlm/Wilted rose.png"},
			{glink : '' , source : "assets/emoticones/wlm/Wink.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/;^^.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/=B.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/angry.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/are you for real .png"},
			{glink : '' , source : "assets/emoticones/yolks/24/beaten.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/boo!.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/bouaaaaah.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/brains...!.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/brzzzzz.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/burnt.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/confident.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/dark mood.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/disapointed.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/disappearing.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/dizzy.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/enjoying mah playlist.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/evilish.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/eyes on fire.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/faill.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/gangs.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/graffiti.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/grin.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/have a nice day.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/hidden.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/high.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/hope my fake smile works again.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/ignoring.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/in love.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/indifferent .png"},
			{glink : '' , source : "assets/emoticones/yolks/24/innocent.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/ka boom.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/lll._..png"},
			{glink : '' , source : "assets/emoticones/yolks/24/mah (chilling).png"},
			{glink : '' , source : "assets/emoticones/yolks/24/meaw.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/ninja.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/nom nom.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/nose bleed.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/nose pick.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/oh noes.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/oh u !.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/omg.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/on fire.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/on fire2.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/ouch...it hurts.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/O_O.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/pissed off.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/psychotic.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/relief.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/scared.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/secret laugh.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/serious business.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/shocked...again.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/shocked.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/shout.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/shy.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/sick.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/slow.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/snooty.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/tastey.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/teeth brushing .png"},
			{glink : '' , source : "assets/emoticones/yolks/24/that dood is up to something.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/TT TT.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/want !.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/want.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/we all gonna die.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/whisper.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/whistle.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/wut.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/X3.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/XD.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/x_x.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/yaeh am not durnk.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/yarr.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/yo !.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/you seem to be serious.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/you're kidding, right.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/yum.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/yuush.png"},
			{glink : '' , source : "assets/emoticones/yolks/24/² z  Z .png"},
			{glink : '' , source : "assets/emoticones/yolks/24/² z Z.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/;^^.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/=B.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/angry.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/are you for real .png"},
			{glink : '' , source : "assets/emoticones/yolks/32/beaten.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/boo!.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/bouaaaaah.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/brains...!.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/brzzzzz.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/burnt.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/confident.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/dark mood.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/disapointed.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/disappearing.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/dizzy.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/enjoying mah playlist.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/evilish.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/eyes on fire.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/faill.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/gangs.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/graffiti.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/grin.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/have a nice day.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/hidden.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/high.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/hope my fake smile works again.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/ignoring.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/in love.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/indifferent .png"},
			{glink : '' , source : "assets/emoticones/yolks/32/innocent.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/ka boom.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/lll._..png"},
			{glink : '' , source : "assets/emoticones/yolks/32/mah (chilling).png"},
			{glink : '' , source : "assets/emoticones/yolks/32/meaw.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/ninja.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/nom nom.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/nose bleed.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/nose pick.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/oh noes.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/oh u !.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/omg.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/on fire.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/on fire2.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/ouch...it hurts.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/O_O.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/pissed off.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/psychotic.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/relief.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/scared.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/secret laugh.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/serious business.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/shocked...again.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/shocked.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/shout.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/shy.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/sick.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/slow.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/snooty.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/tastey.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/teeth brushing .png"},
			{glink : '' , source : "assets/emoticones/yolks/32/that dood is up to something.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/TT TT.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/want !.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/want.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/we all gonna die.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/whisper.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/whistle.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/wut.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/X3.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/XD.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/x_x.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/yaeh am not durnk.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/yarr.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/yo !.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/you seem to be serious.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/you're kidding, right.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/yum.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/yuush.png"},
			{glink : '' , source : "assets/emoticones/yolks/32/² z  Z .png"},
			{glink : '' , source : "assets/emoticones/yolks/32/² z Z.png"}
		]);
		
		public static var s2emoticones24 : ArrayCollection = new ArrayCollection([
			{link:":f", glink : "" , source : "assets/emoticones/2s/24/anger.png",width:24,height:24},
			{link:":F", glink : "" , source : "assets/emoticones/2s/24/anger.png",width:24,height:24},			
			{link:"\\(:b\\)", glink : "" , source : "assets/emoticones/2s/24/burn.PNG",width:24,height:24},
			{link:"\\(:B\\)", glink : "" , source : "assets/emoticones/2s/24/burn.PNG",width:24,height:24},
			{link:":c", glink : "" , source : "assets/emoticones/2s/24/confused.PNG",width:24,height:24},
			{link:":C", glink : "" , source : "assets/emoticones/2s/24/confused.PNG",width:24,height:24},
			{link:"\\(:h\\)", glink : "" , source : "assets/emoticones/2s/24/cool.PNG",width:24,height:24},
			{link:"\\(:H\\)", glink : "" , source : "assets/emoticones/2s/24/cool.PNG",width:24,height:24},
			{link:"\\|\\'\\(", glink : "" , source : "assets/emoticones/2s/24/cry.PNG",width:24,height:24},						
			{link:":@", glink : "" , source : "assets/emoticones/2s/24/fire.PNG",width:24,height:24},
			{link:":\\-P", glink : "" , source : "assets/emoticones/2s/24/grimace.PNG",width:24,height:24},
			{link:":\\-p", glink : "" , source : "assets/emoticones/2s/24/grimace.PNG",width:24,height:24},
			{link:":\\-@", glink : "" , source : "assets/emoticones/2s/24/icon_angry.png",width:24,height:24},			
			{link:":oc", glink : "" , source : "assets/emoticones/2s/24/icon_confused.png",width:24,height:24},
			{link:":OC", glink : "" , source : "assets/emoticones/2s/24/icon_confused.png",width:24,height:24},
			{link:":oC", glink : "" , source : "assets/emoticones/2s/24/icon_confused.png",width:24,height:24},
			{link:":Oc", glink : "" , source : "assets/emoticones/2s/24/icon_confused.png",width:24,height:24},
			{link:"\\(h\\)", glink : "" , source : "assets/emoticones/2s/24/icon_cool.png",width:24,height:24},
			{link:"\\(H\\)", glink : "" , source : "assets/emoticones/2s/24/icon_cool.png",width:24,height:24},			
			{link:":\\'\\(", glink : "" , source : "assets/emoticones/2s/24/icon_cry.png",width:24,height:24},
			{link:":\\-O", glink : "" , source : "assets/emoticones/2s/24/icon_eek.png",width:24,height:24},
			{link:":\\-o", glink : "" , source : "assets/emoticones/2s/24/icon_eek.png",width:24,height:24},			
			{link:"\\-o@", glink : "" , source : "assets/emoticones/2s/24/icon_ft.png",width:24,height:24},
			{link:"\\-O@", glink : "" , source : "assets/emoticones/2s/24/icon_ft.png",width:24,height:24},			
			{link:"\\<3", glink : "" , source : "assets/emoticones/2s/24/icon_heart.png",width:24,height:24},
			{link:":d", glink : "" , source : "assets/emoticones/2s/24/icon_lol.png",width:24,height:24},
			{link:":D", glink : "" , source : "assets/emoticones/2s/24/icon_lol.png",width:24,height:24},
			{link:":\\-\\$", glink : "" , source : "assets/emoticones/2s/24/icon_lovely.png",width:24,height:24},			
			{link:"\\(8\\)", glink : "" , source : "assets/emoticones/2s/24/icon_music.png",width:24,height:24},			
			{link:":\\?", glink : "" , source : "assets/emoticones/2s/24/icon_question.png",width:24,height:24},						
			{link:":\\-#", glink : "" , source : "assets/emoticones/2s/24/icon_razz.png",width:24,height:24},
			{link:":\\(", glink : "" , source : "assets/emoticones/2s/24/icon_sad.png",width:24,height:24},			
			{link:":\\$", glink : "" , source : "assets/emoticones/2s/24/icon_shame.png",width:24,height:24},			
			{link:":b", glink : "" , source : "assets/emoticones/2s/24/icon_shuai.png",width:24,height:24},
			{link:":B", glink : "" , source : "assets/emoticones/2s/24/icon_shuai.png",width:24,height:24},			
			{link:"\\|:\\)", glink : "" , source : "assets/emoticones/2s/24/icon_sleep.png",width:24,height:24},			
			{link:":\\)", glink : "" , source : "assets/emoticones/2s/24/icon_smile.png",width:24,height:24},
			{link:":s", glink : "" , source : "assets/emoticones/2s/24/icon_sweat.png",width:24,height:24},
			{link:":S", glink : "" , source : "assets/emoticones/2s/24/icon_sweat.png",width:24,height:24},
			{link:":p", glink : "" , source : "assets/emoticones/2s/24/icon_tong.png",width:24,height:24},
			{link:":P", glink : "" , source : "assets/emoticones/2s/24/icon_tong.png",width:24,height:24},
			{link:"\\<O3", glink : "" , source : "assets/emoticones/2s/24/love.PNG",width:24,height:24},
			{link:"\\<o3", glink : "" , source : "assets/emoticones/2s/24/love.PNG",width:24,height:24},			
			{link:":o\\$", glink : "" , source : "assets/emoticones/2s/24/prettiness.PNG",width:24,height:24},
			{link:":O\\$", glink : "" , source : "assets/emoticones/2s/24/prettiness.PNG",width:24,height:24},
			{link:":o\\?", glink : "" , source : "assets/emoticones/2s/24/question.PNG",width:24,height:24},
			{link:":O\\?", glink : "" , source : "assets/emoticones/2s/24/question.PNG",width:24,height:24},
			{link:":o\\(\\)", glink : "" , source : "assets/emoticones/2s/24/shout.PNG",width:24,height:24},
			{link:":O\\(\\)", glink : "" , source : "assets/emoticones/2s/24/shout.PNG",width:24,height:24},
			{link:":o\\)\\)", glink : "" , source : "assets/emoticones/2s/24/slobber.PNG",width:24,height:24},
			{link:":O\\)\\)", glink : "" , source : "assets/emoticones/2s/24/slobber.PNG",width:24,height:24},			
			{link:":-\\)", glink : "" , source : "assets/emoticones/2s/24/smile.PNG",width:24,height:24},
			{link:"\\-o\\(", glink : "" , source : "assets/emoticones/2s/24/spook.PNG",width:24,height:24},
			{link:"\\-O\\(", glink : "" , source : "assets/emoticones/2s/24/spook.PNG",width:24,height:24},			
			{link:":\\-\\|", glink : "" , source : "assets/emoticones/2s/24/startle.PNG",width:24,height:24},
			{link:":\\|", glink : "" , source : "assets/emoticones/2s/24/surprise.PNG",width:24,height:24},			
			{link:":-s", glink : "" , source : "assets/emoticones/2s/24/sweat.PNG",width:24,height:24},
			{link:":-S", glink : "" , source : "assets/emoticones/2s/24/sweat.PNG",width:24,height:24},
			{link:"\\|:P", glink : "" , source : "assets/emoticones/2s/24/thirst.PNG",width:24,height:24},
			{link:"\\|:p", glink : "" , source : "assets/emoticones/2s/24/thirst.PNG",width:24,height:24},			
			{link:":m", glink : "" , source : "assets/emoticones/2s/24/miao.PNG",width:24,height:24},
			{link:":M", glink : "" , source : "assets/emoticones/2s/24/miao.PNG",width:24,height:24},			
			{link:"\\+o\\(", glink : "" , source : "assets/emoticones/2s/24/vomit.PNG",width:24,height:24}
		]);


	}
}