<?php

/**
 * CarCouleur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    car
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class CarCouleur extends BaseCarCouleur
{
	public function __toString(){
		return $this->getTitle();
	}

        public static function getAll($id){
            $q = Doctrine_Query::create ()->from ( 'CarCouleur m' )->where("m.active = 1")->orderBy("m.title asc");
            return $q->execute ();
        }
}