<?php
class Errors{
	const MAILEXIST = "MAILEXIST";
	const INVITATIONEXIST = "INVITATIONEXIST";	
	const ALREADYGROUPSUBSCRIBE = "ALREADYGROUPSUBSCRIBE";
	const ALREADYTOPICSUBSCRIBE = "ALREADYTOPICSUBSCRIBE";
}
?>