/*!
 * Ext JS Library 3.3.1
 * Copyright(c) 2006-2010 Sencha Inc.
 * licensing@sencha.com
 * http://www.sencha.com/license
 */
// some data used in the examples
Ext.namespace('Ext.exampledata');

Ext.exampledata.states = [
        ['AL', 'Alabama', 'The Heart of Dixie'],
        ['AK', 'Alaska', 'The Land of the Midnight Sun'],
        ['AZ', 'Arizona', 'The Grand Canyon State'],
        ['AR', 'Arkansas', 'The Natural State'],
        ['CA', 'California', 'The Golden State'],
        ['CO', 'Colorado', 'The Mountain State'],
        ['CT', 'Connecticut', 'The Constitution State'],
        ['DE', 'Delaware', 'The First State'],
        ['DC', 'District of Columbia', "The Nation's Capital"],
        ['FL', 'Florida', 'The Sunshine State'],
        ['GA', 'Georgia', 'The Peach State'],
        ['HI', 'Hawaii', 'The Aloha State'],
        ['ID', 'Idaho', 'Famous Potatoes'],
        ['IL', 'Illinois', 'The Prairie State'],
        ['IN', 'Indiana', 'The Hospitality State'],
        ['IA', 'Iowa', 'The Corn State'],
        ['KS', 'Kansas', 'The Sunflower State'],
        ['KY', 'Kentucky', 'The Bluegrass State'],
        ['LA', 'Louisiana', 'The Bayou State'],
        ['ME', 'Maine', 'The Pine Tree State'],
        ['MD', 'Maryland', 'Chesapeake State'],
        ['MA', 'Massachusetts', 'The Spirit of America'],
        ['MI', 'Michigan', 'Great Lakes State'],
        ['MN', 'Minnesota', 'North Star State'],
        ['MS', 'Mississippi', 'Magnolia State'],
        ['MO', 'Missouri', 'Show Me State'],
        ['MT', 'Montana', 'Big Sky Country'],
        ['NE', 'Nebraska', 'Beef State'],
        ['NV', 'Nevada', 'Silver State'],
        ['NH', 'New Hampshire', 'Granite State'],
        ['NJ', 'New Jersey', 'Garden State'],
        ['NM', 'New Mexico', 'Land of Enchantment'],
        ['NY', 'New York', 'Empire State'],
        ['NC', 'North Carolina', 'First in Freedom'],
        ['ND', 'North Dakota', 'Peace Garden State'],
        ['OH', 'Ohio', 'The Heart of it All'],
        ['OK', 'Oklahoma', 'Oklahoma is OK'],
        ['OR', 'Oregon', 'Pacific Wonderland'],
        ['PA', 'Pennsylvania', 'Keystone State'],
        ['RI', 'Rhode Island', 'Ocean State'],
        ['SC', 'South Carolina', 'Nothing Could be Finer'],
        ['SD', 'South Dakota', 'Great Faces, Great Places'],
        ['TN', 'Tennessee', 'Volunteer State'],
        ['TX', 'Texas', 'Lone Star State'],
        ['UT', 'Utah', 'Salt Lake State'],
        ['VT', 'Vermont', 'Green Mountain State'],
        ['VA', 'Virginia', 'Mother of States'],
        ['WA', 'Washington', 'Green Tree State'],
        ['WV', 'West Virginia', 'Mountain State'],
        ['WI', 'Wisconsin', "America's Dairyland"],
        ['WY', 'Wyoming', 'Like No Place on Earth']
    ];


    Ext.exampledata.mois = [
        ['1', 'Janvier'],
        ['2', 'Février'],
        ['3', 'Mars'],
        ['4', 'Avril'],
        ['5', 'Mai'],
        ['6', 'Juin'],
        ['7', 'Juillet'],
        ['8', 'Août'],
        ['9', 'Septembre'],
        ['10', 'Octobre'],
        ['11', 'Novembre'],
        ['12', 'Décembre']
    ];

    Ext.exampledata.portes = [
        ['2', '2 Portes'],
        ['3', '3 Portes'],
        ['4', '4 Portes'],
        ['5', '5 Portes']
    ];


    Ext.exampledata.fiscale = [
        ['1','1'],
        ['2','2'],
        ['3','3'],
        ['4','4'],
        ['5','5'],
        ['6','6'],
        ['7','7'],
        ['8','8'],
        ['9','9'],
        ['10','10'],
        ['11','11'],
        ['12','12'],
        ['13','13'],
        ['14','14'],
        ['15','15'],
        ['16','16'],
        ['17','17'],
        ['18','18'],
        ['19','19'],
        ['20','20'],
        ['21','21'],
        ['22','22'],
        ['23','23'],
        ['24','24'],
        ['25','25'],
        ['26','26'],
        ['27','27'],
        ['28','28'],
        ['29','29'],
        ['30','30'],
        ['31','31'],
        ['32','32'],
        ['33','33'],
        ['34','34'],
        ['35','35'],
        ['36','36'],
        ['37','37'],
        ['38','38'],
        ['39','39'],
        ['40','40'],
        ['41','41'],
        ['42','42'],
        ['43','43'],
        ['44','44'],
        ['45','45'],
        ['46','46'],
        ['47','47'],
        ['48','48'],
        ['49','49'],
        ['50','50'],
        ['51','51'],
        ['52','52'],
        ['53','53'],
        ['54','54'],
        ['55','55'],
        ['56','56'],
        ['57','57'],
        ['58','58'],
        ['59','59'],
        ['60','60']
    ];