<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiContacts', 'doctrine');

/**
 * BaseAmjiContacts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_user
 * @property integer $idamji_invite
 * @property AmjiUser $AmjiUser
 * 
 * @method integer      getIdamjiUser()    Returns the current record's "idamji_user" value
 * @method integer      getIdamjiInvite()  Returns the current record's "idamji_invite" value
 * @method AmjiUser     getAmjiUser()      Returns the current record's "AmjiUser" value
 * @method AmjiContacts setIdamjiUser()    Sets the current record's "idamji_user" value
 * @method AmjiContacts setIdamjiInvite()  Sets the current record's "idamji_invite" value
 * @method AmjiContacts setAmjiUser()      Sets the current record's "AmjiUser" value
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiContacts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_contacts');
        $this->hasColumn('idamji_user', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('idamji_invite', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmjiUser', array(
             'local' => 'idamji_invite',
             'foreign' => 'idamji_user'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}