<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiEventAttachment', 'doctrine');

/**
 * BaseAmjiEventAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_event
 * @property integer $idamji_file
 * @property AmjiFile $AmjiFile
 * @property AmjiEvent $AmjiEvent
 * 
 * @method integer             getIdamjiEvent()  Returns the current record's "idamji_event" value
 * @method integer             getIdamjiFile()   Returns the current record's "idamji_file" value
 * @method AmjiFile            getAmjiFile()     Returns the current record's "AmjiFile" value
 * @method AmjiEvent           getAmjiEvent()    Returns the current record's "AmjiEvent" value
 * @method AmjiEventAttachment setIdamjiEvent()  Sets the current record's "idamji_event" value
 * @method AmjiEventAttachment setIdamjiFile()   Sets the current record's "idamji_file" value
 * @method AmjiEventAttachment setAmjiFile()     Sets the current record's "AmjiFile" value
 * @method AmjiEventAttachment setAmjiEvent()    Sets the current record's "AmjiEvent" value
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiEventAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_event_attachment');
        $this->hasColumn('idamji_event', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('idamji_file', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmjiFile', array(
             'local' => 'idamji_file',
             'foreign' => 'idamji_file'));

        $this->hasOne('AmjiEvent', array(
             'local' => 'idamji_event',
             'foreign' => 'idamji_event'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}