<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiCastRequest', 'doctrine');

/**
 * BaseAmjiCastRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_request
 * @property integer $iduser
 * @property integer $active
 * @property AmjiUser $AmjiUser
 * @property AmjiRequest $AmjiRequest
 * 
 * @method integer         getIdamjiRequest()  Returns the current record's "idamji_request" value
 * @method integer         getIduser()         Returns the current record's "iduser" value
 * @method integer         getActive()         Returns the current record's "active" value
 * @method AmjiUser        getAmjiUser()       Returns the current record's "AmjiUser" value
 * @method AmjiRequest     getAmjiRequest()    Returns the current record's "AmjiRequest" value
 * @method AmjiCastRequest setIdamjiRequest()  Sets the current record's "idamji_request" value
 * @method AmjiCastRequest setIduser()         Sets the current record's "iduser" value
 * @method AmjiCastRequest setActive()         Sets the current record's "active" value
 * @method AmjiCastRequest setAmjiUser()       Sets the current record's "AmjiUser" value
 * @method AmjiCastRequest setAmjiRequest()    Sets the current record's "AmjiRequest" value
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiCastRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_cast_request');
        $this->hasColumn('idamji_request', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('iduser', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmjiUser', array(
             'local' => 'iduser',
             'foreign' => 'idamji_user'));

        $this->hasOne('AmjiRequest', array(
             'local' => 'idamji_request',
             'foreign' => 'idamji_request'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}