<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiRequest', 'doctrine');

/**
 * BaseAmjiRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_request
 * @property string $title
 * @property string $content
 * @property integer $iduser
 * @property integer $idpriorite
 * @property integer $idtype
 * @property AmjiUser $AmjiUser
 * @property AmjiPriorite $AmjiPriorite
 * @property AmjiType $AmjiType
 * @property Doctrine_Collection $AmjiResponse
 * 
 * @method integer             getIdamjiRequest()  Returns the current record's "idamji_request" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method string              getContent()        Returns the current record's "content" value
 * @method integer             getIduser()         Returns the current record's "iduser" value
 * @method integer             getIdpriorite()     Returns the current record's "idpriorite" value
 * @method integer             getIdtype()         Returns the current record's "idtype" value
 * @method AmjiUser            getAmjiUser()       Returns the current record's "AmjiUser" value
 * @method AmjiPriorite        getAmjiPriorite()   Returns the current record's "AmjiPriorite" value
 * @method AmjiType            getAmjiType()       Returns the current record's "AmjiType" value
 * @method Doctrine_Collection getAmjiResponse()   Returns the current record's "AmjiResponse" collection
 * @method AmjiRequest         setIdamjiRequest()  Sets the current record's "idamji_request" value
 * @method AmjiRequest         setTitle()          Sets the current record's "title" value
 * @method AmjiRequest         setContent()        Sets the current record's "content" value
 * @method AmjiRequest         setIduser()         Sets the current record's "iduser" value
 * @method AmjiRequest         setIdpriorite()     Sets the current record's "idpriorite" value
 * @method AmjiRequest         setIdtype()         Sets the current record's "idtype" value
 * @method AmjiRequest         setAmjiUser()       Sets the current record's "AmjiUser" value
 * @method AmjiRequest         setAmjiPriorite()   Sets the current record's "AmjiPriorite" value
 * @method AmjiRequest         setAmjiType()       Sets the current record's "AmjiType" value
 * @method AmjiRequest         setAmjiResponse()   Sets the current record's "AmjiResponse" collection
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_request');
        $this->hasColumn('idamji_request', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('iduser', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('idpriorite', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('idtype', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmjiUser', array(
             'local' => 'iduser',
             'foreign' => 'idamji_user'));

        $this->hasOne('AmjiPriorite', array(
             'local' => 'idpriorite',
             'foreign' => 'idamji_priorite'));

        $this->hasOne('AmjiType', array(
             'local' => 'idtype',
             'foreign' => 'idamji_type'));

        $this->hasMany('AmjiResponse', array(
             'local' => 'idamji_request',
             'foreign' => 'idrequest'));
    }
}