<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiSubscribe', 'doctrine');

/**
 * BaseAmjiSubscribe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_user
 * @property integer $idamji_type
 * 
 * @method integer       getIdamjiUser()  Returns the current record's "idamji_user" value
 * @method integer       getIdamjiType()  Returns the current record's "idamji_type" value
 * @method AmjiSubscribe setIdamjiUser()  Sets the current record's "idamji_user" value
 * @method AmjiSubscribe setIdamjiType()  Sets the current record's "idamji_type" value
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiSubscribe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_subscribe');
        $this->hasColumn('idamji_user', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('idamji_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}