<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiEventUser', 'doctrine');

/**
 * BaseAmjiEventUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_user
 * @property integer $idamji_event
 * @property AmjiUser $AmjiUser
 * @property AmjiEvent $AmjiEvent
 * 
 * @method integer       getIdamjiUser()   Returns the current record's "idamji_user" value
 * @method integer       getIdamjiEvent()  Returns the current record's "idamji_event" value
 * @method AmjiUser      getAmjiUser()     Returns the current record's "AmjiUser" value
 * @method AmjiEvent     getAmjiEvent()    Returns the current record's "AmjiEvent" value
 * @method AmjiEventUser setIdamjiUser()   Sets the current record's "idamji_user" value
 * @method AmjiEventUser setIdamjiEvent()  Sets the current record's "idamji_event" value
 * @method AmjiEventUser setAmjiUser()     Sets the current record's "AmjiUser" value
 * @method AmjiEventUser setAmjiEvent()    Sets the current record's "AmjiEvent" value
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiEventUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_event_user');
        $this->hasColumn('idamji_user', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('idamji_event', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmjiUser', array(
             'local' => 'idamji_user',
             'foreign' => 'idamji_user'));

        $this->hasOne('AmjiEvent', array(
             'local' => 'idamji_event',
             'foreign' => 'idamji_event'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}