<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Priorite', 'doctrine');

/**
 * BasePriorite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idpriorite
 * @property string $libelle
 * @property Doctrine_Collection $Request
 * 
 * @method integer             getIdpriorite() Returns the current record's "idpriorite" value
 * @method string              getLibelle()    Returns the current record's "libelle" value
 * @method Doctrine_Collection getRequest()    Returns the current record's "Request" collection
 * @method Priorite            setIdpriorite() Sets the current record's "idpriorite" value
 * @method Priorite            setLibelle()    Sets the current record's "libelle" value
 * @method Priorite            setRequest()    Sets the current record's "Request" collection
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePriorite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('priorite');
        $this->hasColumn('idpriorite', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('libelle', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '45',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Request', array(
             'local' => 'idpriorite',
             'foreign' => 'priorite'));
    }
}