<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiGroup', 'doctrine');

/**
 * BaseAmjiGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamjid_group
 * @property string $title
 * @property integer $owner
 * @property string $description
 * @property integer $active
 * @property Doctrine_Collection $AmjiUser
 * 
 * @method integer             getIdamjidGroup()  Returns the current record's "idamjid_group" value
 * @method string              getTitle()         Returns the current record's "title" value
 * @method integer             getOwner()         Returns the current record's "owner" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method integer             getActive()        Returns the current record's "active" value
 * @method Doctrine_Collection getAmjiUser()      Returns the current record's "AmjiUser" collection
 * @method AmjiGroup           setIdamjidGroup()  Sets the current record's "idamjid_group" value
 * @method AmjiGroup           setTitle()         Sets the current record's "title" value
 * @method AmjiGroup           setOwner()         Sets the current record's "owner" value
 * @method AmjiGroup           setDescription()   Sets the current record's "description" value
 * @method AmjiGroup           setActive()        Sets the current record's "active" value
 * @method AmjiGroup           setAmjiUser()      Sets the current record's "AmjiUser" collection
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_group');
        $this->hasColumn('idamjid_group', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '100',
             ));
        $this->hasColumn('owner', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AmjiUser', array(
             'local' => 'owner',
             'foreign' => 'idamji_user'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}