<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiStatut', 'doctrine');

/**
 * BaseAmjiStatut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_statut
 * @property string $libelle
 * @property Doctrine_Collection $AmjiUser
 * 
 * @method integer             getIdamjiStatut()  Returns the current record's "idamji_statut" value
 * @method string              getLibelle()       Returns the current record's "libelle" value
 * @method Doctrine_Collection getAmjiUser()      Returns the current record's "AmjiUser" collection
 * @method AmjiStatut          setIdamjiStatut()  Sets the current record's "idamji_statut" value
 * @method AmjiStatut          setLibelle()       Sets the current record's "libelle" value
 * @method AmjiStatut          setAmjiUser()      Sets the current record's "AmjiUser" collection
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiStatut extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_statut');
        $this->hasColumn('idamji_statut', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('libelle', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '100',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AmjiUser', array(
             'local' => 'idamji_statut',
             'foreign' => 'idamji_statut'));
    }
}