<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AmjiResponseAttachment', 'doctrine');

/**
 * BaseAmjiResponseAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idamji_response
 * @property integer $idamji_file
 * 
 * @method integer                getIdamjiResponse()  Returns the current record's "idamji_response" value
 * @method integer                getIdamjiFile()      Returns the current record's "idamji_file" value
 * @method AmjiResponseAttachment setIdamjiResponse()  Sets the current record's "idamji_response" value
 * @method AmjiResponseAttachment setIdamjiFile()      Sets the current record's "idamji_file" value
 * 
 * @package    amji
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseAmjiResponseAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amji_response_attachment');
        $this->hasColumn('idamji_response', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('idamji_file', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}