# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  a:

    pager_nb_links: 5
    
    # We use this to bring in our own API keys and such, you need to go get your own
    <?php if (file_exists(dirname(__FILE__) . '/punk-demo-app.yml')) require dirname(__FILE__) . '/punk-demo-app.yml' ?>

    # includes apostrophe css into the project
    use_bundled_stylesheet: true
    
    # default button order for P'unk Projects
    global_button_order:
      - blog
      - events
      - media
      - categories
      - tags
      - users   
      - reorganize
    
    persistent_global_toolbar: true # false if you want to hide the global toolbar to logged-out visitors
    
    # If true, there will be a language switcher next to the login/logout button
    i18n_switch: true
    i18n_languages: [en, fr, de, es, ru]
