<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/01/26 15:14:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=amji',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
