AmjiEmoticones:
  connection: doctrine
  tableName: amji_emoticones
  columns:
    idamji_emoticones:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    racourci:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    image:
      type: string(200)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
AmjiFile:
  connection: doctrine
  tableName: amji_file
  columns:
    idamji_file:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    content:
      type: blob()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
AmjiInvitation:
  connection: doctrine
  tableName: amji_invitation
  columns:
    idamji_user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    idamji_invite:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    message:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
AmjiPriorite:
  connection: doctrine
  tableName: amji_priorite
  columns:
    idamji_priorite:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    libelle:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AmjiRequest:
      local: idamji_priorite
      foreign: idpriorite
      type: many
AmjiRequest:
  connection: doctrine
  tableName: amji_request
  columns:
    idamji_request:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    title:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    content:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    iduser:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idpriorite:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idtype:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AmjiUser:
      local: iduser
      foreign: idamji_user
      type: one
    AmjiPriorite:
      local: idpriorite
      foreign: idamji_priorite
      type: one
    AmjiType:
      local: idtype
      foreign: idamji_type
      type: one
    AmjiResponse:
      local: idamji_request
      foreign: idrequest
      type: many
AmjiRequestAttachment:
  connection: doctrine
  tableName: amji_request_attachment
  columns:
    idamji_file:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    idamji_request:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
AmjiResponse:
  connection: doctrine
  tableName: amji_response
  columns:
    idamji_response:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    content:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    iduser:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idrequest:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idresponse:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    AmjiUser:
      local: iduser
      foreign: idamji_user
      type: one
    AmjiRequest:
      local: idrequest
      foreign: idamji_request
      type: one
    AmjiResponse:
      local: idamji_response
      foreign: idresponse
      type: many
AmjiResponseAttachment:
  connection: doctrine
  tableName: amji_response_attachment
  columns:
    idamji_response:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    idamji_file:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
AmjiStatut:
  connection: doctrine
  tableName: amji_statut
  columns:
    idamji_statut:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    libelle:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AmjiUser:
      local: idamji_statut
      foreign: idamji_statut
      type: many
AmjiSubscribe:
  connection: doctrine
  tableName: amji_subscribe
  columns:
    idamji_user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    idamji_type:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
AmjiType:
  connection: doctrine
  tableName: amji_type
  columns:
    idamji_type:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    libelle:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    AmjiRequest:
      local: idamji_type
      foreign: idtype
      type: many
AmjiUser:
  connection: doctrine
  tableName: amji_user
  columns:
    idamji_user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    pseudo:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nom:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    prenom:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    adr:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tel:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    etudiant:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ecole:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    niveau:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    salarie:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    statut:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    societe:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    idamji_statut:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    AmjiStatut:
      local: idamji_statut
      foreign: idamji_statut
      type: one
    AmjiRequest:
      local: idamji_user
      foreign: iduser
      type: many
    AmjiResponse:
      local: idamji_user
      foreign: iduser
      type: many
